# Generated by hand for TanPit drum speed cards

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="DrumCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("card_no", models.PositiveIntegerField()),
                ("rpm", models.PositiveIntegerField()),
                ("measurer", models.CharField(max_length=64)),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.CharField(blank=True, max_length=64)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drum_cards",
                        to="pits.pit",
                    ),
                ),
            ],
            options={
                "ordering": ["pit_id", "card_no"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(voided_at__isnull=True),
                        fields=("pit", "card_no"),
                        name="uniq_active_drum_card_no",
                    )
                ],
            },
        ),
    ]
